"""Initial migration for the ``audit`` app (AccessLog).

The pghistory event model is generated by ``makemigrations`` at startup (dev).
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evento", models.CharField(choices=[("LOGIN", "Inicio de sesión"), ("LOGOUT", "Cierre de sesión"), ("LOGIN_FAILED", "Intento fallido de inicio de sesión")], max_length=16, verbose_name="evento")),
                ("email_intento", models.EmailField(blank=True, default="", max_length=254, verbose_name="email del intento")),
                ("ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="user agent")),
                ("ts", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="timestamp")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="access_logs", to=settings.AUTH_USER_MODEL, verbose_name="usuario")),
            ],
            options={
                "verbose_name": "evento de acceso",
                "verbose_name_plural": "eventos de acceso",
                "ordering": ["-ts"],
                "indexes": [
                    models.Index(fields=["evento", "ts"], name="audit_acces_evento_idx"),
                    models.Index(fields=["usuario", "ts"], name="audit_acces_usuario_idx"),
                ],
            },
        ),
    ]
