# Generated by Django 5.2.1 on 2026-08-26 04:31

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_accesslog_append_only'),
        ('pghistory', '0006_delete_aggregateevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('evento', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento fallido de inicio de sesión')], max_length=16, verbose_name='evento')),
                ('email_intento', models.EmailField(blank=True, default='', max_length=254, verbose_name='email del intento')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='audit_acces_evento_f5feb3_idx',
            old_name='audit_acces_evento_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='audit_acces_usuario_353946_idx',
            old_name='audit_acces_usuario_idx',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='accesslog',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "audit_accesslogevent" ("email_intento", "evento", "id", "ip", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ts", "user_agent", "usuario_id") VALUES (NEW."email_intento", NEW."evento", NEW."id", NEW."ip", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."ts", NEW."user_agent", NEW."usuario_id"); RETURN NULL;', hash='c0071ba5d6127678235caee8553aa38c620a12b8', operation='INSERT', pgid='pgtrigger_insert_insert_060c2', table='audit_accesslog', when='AFTER')),
        ),
        migrations.AddField(
            model_name='accesslogevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='accesslogevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='audit.accesslog'),
        ),
        migrations.AddField(
            model_name='accesslogevent',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
