"""Initial migration for the ``ledger`` app (Certificate).

The pghistory event model and the simple-history table are generated by
``makemigrations`` at container startup (dev).
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=40, unique=True, verbose_name="código")),
                ("asunto", models.CharField(max_length=200, verbose_name="asunto")),
                ("emitido_a", models.CharField(blank=True, default="", max_length=200, verbose_name="emitido a")),
                ("veredicto", models.CharField(choices=[("CONFORME", "Conforme"), ("NO_CONFORME", "No conforme")], default="CONFORME", max_length=16, verbose_name="veredicto")),
                ("observaciones", models.TextField(blank=True, default="", verbose_name="observaciones")),
                ("estado", models.CharField(choices=[("BORRADOR", "Borrador"), ("FIRMADO", "Firmado"), ("REEMPLAZADO", "Reemplazado")], default="BORRADOR", max_length=16, verbose_name="estado")),
                ("firmada", models.BooleanField(default=False, verbose_name="firmada")),
                ("firma_ts", models.DateTimeField(blank=True, null=True, verbose_name="fecha de firma")),
                ("firma_hash", models.CharField(blank=True, default="", max_length=64, verbose_name="hash de firma")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                ("actualizado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="certificados_actualizados", to=settings.AUTH_USER_MODEL, verbose_name="actualizado por")),
                ("creado_por", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="certificados_creados", to=settings.AUTH_USER_MODEL, verbose_name="creado por")),
                ("firmante", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="certificados_firmados", to=settings.AUTH_USER_MODEL, verbose_name="firmante")),
            ],
            options={
                "verbose_name": "certificado",
                "verbose_name_plural": "certificados",
                "ordering": ["-created_at"],
            },
        ),
    ]
