# Generated by Django 5.2.1 on 2026-08-26 04:31

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_certificate_reemplaza'),
        ('pghistory', '0006_delete_aggregateevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('codigo', models.CharField(max_length=40, verbose_name='código')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('emitido_a', models.CharField(blank=True, default='', max_length=200, verbose_name='emitido a')),
                ('veredicto', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No conforme')], default='CONFORME', max_length=16, verbose_name='veredicto')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('REEMPLAZADO', 'Reemplazado')], default='BORRADOR', max_length=16, verbose_name='estado')),
                ('firmada', models.BooleanField(default=False, verbose_name='firmada')),
                ('firma_ts', models.DateTimeField(blank=True, null=True, verbose_name='fecha de firma')),
                ('firma_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='hash de firma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCertificate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40, verbose_name='código')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('emitido_a', models.CharField(blank=True, default='', max_length=200, verbose_name='emitido a')),
                ('veredicto', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No conforme')], default='CONFORME', max_length=16, verbose_name='veredicto')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('REEMPLAZADO', 'Reemplazado')], default='BORRADOR', max_length=16, verbose_name='estado')),
                ('firmada', models.BooleanField(default=False, verbose_name='firmada')),
                ('firma_ts', models.DateTimeField(blank=True, null=True, verbose_name='fecha de firma')),
                ('firma_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='hash de firma')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='creado')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical certificado',
                'verbose_name_plural': 'historical certificados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificate',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ledger_certificateevent" ("actualizado_por_id", "asunto", "codigo", "creado_por_id", "created_at", "emitido_a", "estado", "firma_hash", "firma_ts", "firmada", "firmante_id", "id", "observaciones", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reemplaza_id", "updated_at", "veredicto") VALUES (NEW."actualizado_por_id", NEW."asunto", NEW."codigo", NEW."creado_por_id", NEW."created_at", NEW."emitido_a", NEW."estado", NEW."firma_hash", NEW."firma_ts", NEW."firmada", NEW."firmante_id", NEW."id", NEW."observaciones", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reemplaza_id", NEW."updated_at", NEW."veredicto"); RETURN NULL;', hash='c43c0e22dca2a3e945e9d24a2a8dba154a5f47a1', operation='INSERT', pgid='pgtrigger_insert_insert_ff015', table='ledger_certificate', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='certificate',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ledger_certificateevent" ("actualizado_por_id", "asunto", "codigo", "creado_por_id", "created_at", "emitido_a", "estado", "firma_hash", "firma_ts", "firmada", "firmante_id", "id", "observaciones", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reemplaza_id", "updated_at", "veredicto") VALUES (NEW."actualizado_por_id", NEW."asunto", NEW."codigo", NEW."creado_por_id", NEW."created_at", NEW."emitido_a", NEW."estado", NEW."firma_hash", NEW."firma_ts", NEW."firmada", NEW."firmante_id", NEW."id", NEW."observaciones", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reemplaza_id", NEW."updated_at", NEW."veredicto"); RETURN NULL;', hash='5a4597a798a36767eab140e1419f8220a568d687', operation='UPDATE', pgid='pgtrigger_update_update_61934', table='ledger_certificate', when='AFTER')),
        ),
        migrations.AddField(
            model_name='certificateevent',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='certificateevent',
            name='creado_por',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='certificateevent',
            name='firmante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='firmante'),
        ),
        migrations.AddField(
            model_name='certificateevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='certificateevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ledger.certificate'),
        ),
        migrations.AddField(
            model_name='certificateevent',
            name='reemplaza',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='ledger.certificate', verbose_name='reemplaza a'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='firmante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='firmante'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='reemplaza',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.certificate', verbose_name='reemplaza a'),
        ),
    ]
